name: build and push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - htop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.directory }}
          build-args: GIT_REF=${{ env.GITHUB_SHA }}
          push: ${{ github.event_name == 'push' }}
          tag: eunomie/${{ matrix.directory }}:latest
